# Generated by Django 5.1.4 on 2025-01-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_initial"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="stock",
            name="cantidad",
            field=models.PositiveIntegerField(default=0, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="deposito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.deposito",
                verbose_name="Depósito",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.producto",
                verbose_name="Producto",
            ),
        ),
    ]
