# Generated by Django 5.1.4 on 2025-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_initial"),
        ("stock", "0002_remove_stock_created_at_remove_stock_created_by_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["producto", "deposito"], name="idx_producto_deposito"
            ),
        ),
    ]
