# Generated by Django 5.1.4 on 2025-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remito",
            name="tipo_remito",
            field=models.CharField(
                choices=[
                    ("ajuste", "Ajuste"),
                    ("compra", "Compra"),
                    ("venta", "Venta"),
                    ("interdeposito", "Interdepósito"),
                ],
                max_length=50,
            ),
        ),
    ]
