# Generated by Django 5.1.4 on 2025-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0002_alter_remito_tipo_remito"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="remito",
            options={
                "permissions": [("crear_ajuste", "Puede crear remitos de ajuste")]
            },
        ),
    ]
