# Generated by Django 5.1.4 on 2025-01-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_localidad_pais_alter_cliente_localidad_and_more"),
        ("remitos", "0002_detalleremito_created_at_detalleremito_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provincia",
            name="pais",
        ),
        migrations.DeleteModel(
            name="Localidad",
        ),
        migrations.DeleteModel(
            name="Pais",
        ),
        migrations.DeleteModel(
            name="Provincia",
        ),
    ]
