# Generated by Django 5.1.4 on 2025-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0003_alter_remito_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="remito",
            options={
                "permissions": [("can_create_ajuste", "Puede crear remitos de ajuste")]
            },
        ),
    ]
