# Generated by Django 5.1.4 on 2025-01-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_alter_clientetipo_cliente"),
        ("productos", "0004_alter_producto_descripcion"),
        ("remitos", "0003_remove_provincia_pais_delete_localidad_delete_pais_and_more"),
        ("stock", "0002_stock_created_at_stock_created_by_stock_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remito",
            name="estado_remito",
            field=models.CharField(
                choices=[("activo", "Activo"), ("anulado", "Anulado")],
                default="activo",
                max_length=10,
                verbose_name="Estado del Remito",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="tipo_remito",
            field=models.CharField(
                choices=[
                    ("ajuste", "Ajuste"),
                    ("compra", "Compra"),
                    ("venta", "Venta"),
                    ("interdeposito", "Interdepósito"),
                ],
                default="ajuste",
                max_length=20,
                verbose_name="Tipo de Remito",
            ),
        ),
        migrations.AlterField(
            model_name="detalleremito",
            name="cantidad",
            field=models.PositiveIntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="detalleremito",
            name="precio_unit",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
            ),
        ),
        migrations.AlterField(
            model_name="detalleremito",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="detalleremito",
            name="remito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="remitos.remito",
                verbose_name="Remito",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="dep_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remitos_destino",
                to="stock.deposito",
                verbose_name="Depósito Destino",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="dep_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remitos_origen",
                to="stock.deposito",
                verbose_name="Depósito Origen",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha del Remito"
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="nro_comprobante_asoc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nro Comprobante Asociado"
            ),
        ),
        migrations.DeleteModel(
            name="EstadoRemito",
        ),
        migrations.DeleteModel(
            name="TipoRemito",
        ),
    ]
