# Generated by Django 5.1.4 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0004_alter_remito_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionMoneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(max_length=50, unique=True, verbose_name="Moneda"),
                ),
                (
                    "simbolo",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Símbolo"
                    ),
                ),
                (
                    "conversion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor de Conversión",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="remito",
            options={},
        ),
    ]
