# Generated by Django 5.1.4 on 2025-01-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_alter_clientetipo_cliente"),
        (
            "remitos",
            "0004_alter_remito_estado_remito_alter_remito_tipo_remito_and_more",
        ),
        ("stock", "0002_stock_created_at_stock_created_by_stock_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remito",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="dep_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remitos_destino",
                to="stock.deposito",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="dep_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remitos_origen",
                to="stock.deposito",
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="estado_remito",
            field=models.CharField(
                choices=[("activo", "Activo"), ("anulado", "Anulado")],
                default="activo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="remito",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="remito",
            name="nro_comprobante_asoc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="remito",
            name="tipo_remito",
            field=models.CharField(
                choices=[
                    ("ajuste", "Ajuste"),
                    ("compra", "Compra"),
                    ("venta", "Venta"),
                    ("interdeposito", "Interdepósito"),
                ],
                max_length=50,
            ),
        ),
    ]
