# Generated by Django 5.1.4 on 2025-01-18 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0005_alter_remito_cliente_alter_remito_dep_destino_and_more"),
        ("stock", "0002_stock_created_at_stock_created_by_stock_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remito",
            name="dep_destino",
        ),
        migrations.RemoveField(
            model_name="remito",
            name="dep_origen",
        ),
        migrations.AddField(
            model_name="detalleremito",
            name="dep_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_destino",
                to="stock.deposito",
            ),
        ),
        migrations.AddField(
            model_name="detalleremito",
            name="dep_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_origen",
                to="stock.deposito",
            ),
        ),
    ]
