# Generated by Django 5.1.4 on 2025-01-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remitos", "0005_conversionmoneda_alter_remito_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleremito",
            name="moneda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="remitos.conversionmoneda",
                verbose_name="Moneda",
            ),
        ),
    ]
