# Generated by Django 5.1.4 on 2025-01-26 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDTipo1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("atributo1", models.TextField(blank=True, null=True)),
                ("atributo2", models.TextField(blank=True, null=True)),
                ("atributo3", models.TextField(blank=True, null=True)),
                ("atributo4", models.TextField(blank=True, null=True)),
                ("atributo5", models.TextField(blank=True, null=True)),
                ("pre1", models.TextField(blank=True, null=True)),
                ("pre2", models.TextField(blank=True, null=True)),
                ("pre3", models.TextField(blank=True, null=True)),
                ("pre4", models.TextField(blank=True, null=True)),
                ("pre5", models.TextField(blank=True, null=True)),
                ("suf1", models.TextField(blank=True, null=True)),
                ("suf2", models.TextField(blank=True, null=True)),
                ("suf3", models.TextField(blank=True, null=True)),
                ("suf4", models.TextField(blank=True, null=True)),
                ("suf5", models.TextField(blank=True, null=True)),
                ("cod_alpha", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sinonimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoIDTipo2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("abreviatura", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("abreviatura", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="IDTipo2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("cod_alpha", models.CharField(max_length=3, unique=True)),
                (
                    "IDtipo1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="IDTIPO2",
                        to="productos.idtipo1",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesConcatenada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atributo1", models.TextField(blank=True, null=True)),
                ("atributo2", models.TextField(blank=True, null=True)),
                ("atributo3", models.TextField(blank=True, null=True)),
                ("atributo4", models.TextField(blank=True, null=True)),
                ("atributo5", models.TextField(blank=True, null=True)),
                ("cod_alpha", models.CharField(max_length=13, unique=True)),
                (
                    "IDtipo1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.idtipo1",
                    ),
                ),
                (
                    "IDtipo2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.idtipo2",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.marca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode", models.TextField(blank=True, null=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
