# Generated by Django 5.1.4 on 2025-01-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="loc_col",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.columna",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_dep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.deposito",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_est",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.estante",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_pas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.pasillo",
            ),
        ),
    ]
