# Generated by Django 5.1.4 on 2025-01-26 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("productos", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="loc_col",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.columna",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_dep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.deposito",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_est",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.estante",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="loc_pas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.pasillo",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.rubro",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="desconcatenada",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desconcatenada",
                to="productos.producto",
            ),
        ),
        migrations.AddField(
            model_name="sinonimo",
            name="idtipo1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sinonimos",
                to="productos.idtipo1",
            ),
        ),
        migrations.AddField(
            model_name="idtipo1",
            name="IDtipo2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="idtipo1",
                to="productos.tipoidtipo2",
            ),
        ),
        migrations.AddField(
            model_name="desconcatenada",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.unidad"
            ),
        ),
    ]
