# Generated by Django 5.1.4 on 2025-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_created_at_producto_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.CharField(max_length=255),
        ),
    ]
