# Generated by Django 5.1.4 on 2025-01-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_alter_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDTipo1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("IDtipo2", models.TextField()),
                ("atributo1", models.TextField(blank=True, null=True)),
                ("atributo2", models.TextField(blank=True, null=True)),
                ("atributo3", models.TextField(blank=True, null=True)),
                ("atributo4", models.TextField(blank=True, null=True)),
                ("atributo5", models.TextField(blank=True, null=True)),
                ("pre1", models.TextField(blank=True, null=True)),
                ("pre2", models.TextField(blank=True, null=True)),
                ("pre3", models.TextField(blank=True, null=True)),
                ("pre4", models.TextField(blank=True, null=True)),
                ("pre5", models.TextField(blank=True, null=True)),
                ("suf1", models.TextField(blank=True, null=True)),
                ("suf2", models.TextField(blank=True, null=True)),
                ("suf3", models.TextField(blank=True, null=True)),
                ("suf4", models.TextField(blank=True, null=True)),
                ("suf5", models.TextField(blank=True, null=True)),
                ("cod_alpha", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sinonimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IDTipo2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("cod_alpha", models.CharField(max_length=3, unique=True)),
                (
                    "IDtipo1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="IDTIPO2",
                        to="productos.idtipo1",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="idtipo1",
            name="sinonimos",
            field=models.ManyToManyField(
                blank=True, related_name="idtipo1", to="productos.sinonimo"
            ),
        ),
        migrations.CreateModel(
            name="DesConcatenada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atributo1", models.TextField(blank=True, null=True)),
                ("atributo2", models.TextField(blank=True, null=True)),
                ("atributo3", models.TextField(blank=True, null=True)),
                ("atributo4", models.TextField(blank=True, null=True)),
                ("atributo5", models.TextField(blank=True, null=True)),
                ("cod_alpha", models.CharField(max_length=3, unique=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.producto",
                    ),
                ),
                (
                    "IDtipo1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.idtipo1",
                    ),
                ),
                (
                    "IDtipo2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.idtipo2",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.marca",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.unidad",
                    ),
                ),
            ],
        ),
    ]
