# Generated by Django 5.1.4 on 2025-01-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_idtipo1_marca_sinonimo_unidad_idtipo2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idtipo1",
            name="sinonimos",
        ),
        migrations.AddField(
            model_name="sinonimo",
            name="idtipo1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sinonimos",
                to="productos.idtipo1",
            ),
            preserve_default=False,
        ),
    ]
