# Generated by Django 5.1.4 on 2025-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_remove_idtipo1_sinonimos_sinonimo_idtipo1"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidad",
            name="abreviatura",
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
