# Generated by Django 5.1.4 on 2025-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_unidad_abreviatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desconcatenada",
            name="cod_alpha",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
