# Generated by Django 5.1.4 on 2025-01-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0008_alter_clientetipo_cliente"),
        ("productos", "0008_alter_desconcatenada_cod_alpha"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.rubro",
            ),
        ),
    ]
