# Generated by Django 5.1.4 on 2025-01-25 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_producto_rubro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desconcatenada",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desconcatenadas",
                to="productos.producto",
            ),
        ),
    ]
