# Generated by Django 5.1.4 on 2025-01-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("remitos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="remitos.localidad",
            ),
        ),
        migrations.AddField(
            model_name="clientetipo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AddField(
            model_name="contacto",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.rubro",
            ),
        ),
        migrations.AddField(
            model_name="clientetipo",
            name="tipo_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.tipocliente"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clientes.tipodocumento",
            ),
        ),
    ]
