# Generated by Django 5.1.4 on 2025-01-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoriaArancelaria",
            new_name="CategoriaArca",
        ),
        migrations.RenameField(
            model_name="cliente",
            old_name="abreviatura",
            new_name="fantasia",
        ),
    ]
