# Generated by Django 5.1.4 on 2025-01-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_localidad_pais_alter_cliente_localidad_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localidad",
            name="pais",
        ),
    ]
