# Generated by Django 5.1.4 on 2025-01-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_remove_localidad_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientetipo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tipos",
                to="clientes.cliente",
            ),
        ),
    ]
